Freegan bot tables
catebi/Catebi.Api pull request #36
Opened 2023-12-09 18:14 UTC by tk0nik

Новая схема: freegan и таблицы в ней для бота

2023-12-10 22:48 UTC, lejafo requested changes

2023-12-10 22:48 UTC, lejafo commented on db/schema/init_db_schema.sql
> +grant usage on schema freegan to catebi_admin_role, catebi_user_role, catebi_support_role;
предлагаю использовать название схемы без гласных — frgn

2023-12-10 22:48 UTC, lejafo commented on db/changelog/releases/1.0.0/03._freegan_bot_tables.sql
> +create table freegan.restriction(
вот эти таблички ограничений нужно будет обсудить

2023-12-10 22:48 UTC, lejafo commented on db/changelog/releases/1.0.0/03._freegan_bot_tables.sql
> +create table freegan.keyword(
для ключевых слов добавятся микроправила

2023-12-10 22:48 UTC, lejafo commented on db/changelog/releases/1.0.0/03._freegan_bot_tables.sql
> +	chat_id serial PRIMARY KEY,
primary key c маленькой буквой для единого формата

2023-12-18 19:53 UTC, tk0nik commented on db/changelog/releases/1.0.0/03._freegan_bot_tables.sql
> +create table freegan.restriction(
Напомни, что там с ними не так (кроме потенциальных микроправил)

2023-12-18 19:56 UTC, lejafo commented on db/changelog/releases/1.0.0/03._freegan_bot_tables.sql
> +create table freegan.restriction(
а я отписался в чате по фригану по поводу этих табличек

сейчас сюда зашлю

2023-12-18 20:00 UTC, lejafo commented
@tk0nik 

нам нужно обсудить структуру табличек для фригана в свете разных типов чатов (барахолки, чаты животных) и доп. проверок для отдельной группы ключевых слов

возможные таблички в схеме для фригана

ключевые слова
группы ключевых слов (основные, требующие уточняющих правил)
чаты
группы чатов (барахолки, чаты животных)

2023-12-18 20:04 UTC, tk0nik commented on db/changelog/releases/1.0.0/03._freegan_bot_tables.sql
> +create table freegan.keyword(
Предлагаю единую таблицу сочетаний как вариант. Многие ко многим, три столбца: ID основного кейворда, ID слов, которые должны идти с ним, ID слов, которые исключаются. Это если без типов чатов. Их как раз лучше отсекать таки таблицей ограничений.

2023-12-18 20:58 UTC, lejafo commented on db/changelog/releases/1.0.0/03._freegan_bot_tables.sql
> +create table freegan.keyword(
вот мне кажется что вернее было бы действовать через группы ключевых слов

то есть что-то вроде такого:

чат -> группа чатов(барахолки) -> группы ключевых слов

группы ключевых слов состоят из:
 
- простая группа ключевых слов (не предполагает уточняющих проверок)
- группа ключевых слов с доп.проверками

по первой будет просто через связь доставаться список ключевых слов, а для второй связи будет ссылка на дополнительную группу ключевых слов

наверное плохо объяснил, но давай завтра тогда на эту тему поговорим

смысл в том, чтобы в бд не было ничего кроме идентификаторов ключевых слов (ни регулярок, ни повторного упоминания одного и того же ключевого слова) и все разруливалось через связи между таблицами

для конкретного чата нужно иметь несколько наборов ключевых слов (простой и с доп. проверками)

2023-12-30 12:51 UTC, closed without merging