statistics report view added
catebi/Catebi.Api pull request #67
Opened 2024-03-03 17:04 UTC by tk0nik

2024-03-09 15:06 UTC, lejafo requested changes

2024-03-09 15:06 UTC, lejafo commented on db/changelog/releases/1.0.0/06._cat_views.sql
> +    select '����� ��������� � ��', count(cat_id)
поправить кодировку

2024-03-09 15:06 UTC, lejafo commented on db/changelog/releases/1.0.0/06._cat_views.sql
> +    select '����� ��������� � ��', count(cat_id)
везде в файле

2024-03-09 15:06 UTC, lejafo commented on db/changelog/releases/1.0.0/06._cat_views.sql
> +create view ctb.cat_statistics_output (label, value) as
а что такое (label, value)?

2024-03-29 17:35 UTC, tk0nik commented on db/changelog/releases/1.0.0/06._cat_views.sql
> +    select '����� ��������� � ��', count(cat_id)
Готово

2024-04-07 10:45 UTC, lejafo approved these changes

2024-04-09 11:35 UTC, merged